MODEL:
  META_ARCHITECTURE: "resnet18"
  WEIGHT: ""
  DENSENET: False
DATASETS:
  TRAIN: ("FEC_TRAIN",)
  TEST: ("FEC_TEST",)
SOLVER:
  BASE_LR: 1e-4
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0005
  STEPS: (40000, 45000)
  MAX_ITER: 50000
  IMS_PER_BATCH: 30  # for 8GPUs
  OPTIM: "Adam"
